### ISSUE TITLE
bug: 'self' captured by a closure before all members were initialized

### ISSUE THREAD

**Issue by notmgsk** [tmandry/Swindler#66] opened 2020-05-04 03:14 UTC
xcode Version 11.3.1 (11C504)

**Comment by Luccifer** [comment] 2020-06-27 18:21
He meant Screen.swift file init() function where "self" is actually inbound init

**Comment by Luccifer** [comment] 2020-06-29 17:20
You can reproduce the bug if u add source files of Swindler 9like drag and drop) to new pros with dependance-pods (PromiseKit/AXSwift)

**Comment by talaviram** [comment] 2021-01-04 22:31
My apologizes. I've commented on the commit.
Deleting my comment which is dupe of this issue.

**Comment by tmandry** [comment] 2021-01-05 06:53
This was failing yesterday but is now fixed on master. CI runs Xcode 11.3 so should prevent this issue from coming up again in the future. 

Feel free to reopen if not fixed. Thanks!

**Closed** 2021-01-05 06:54 UTC
